<?php

/**
 * @file
 * Provides payments method for Drupal Commerce
 */


/**
 * Implements hook_commerce_payment_method_info().
 */
function flg_payment_commerce_payment_method_info() {
  $payment_methods = array();

  $payment_methods['direct_deposit'] = array(
    'title' => t('Direct Deposit'),
    'description' => '',
    'active' => TRUE,
  );

  $payment_methods['art_money'] = array(
    'title' => t('Art money'),
    'description' => '',
    'active' => TRUE,
  );

  $payment_methods['labuy'] = array(
    'title' => t('Labuy'),
    'description' => '',
    'active' => TRUE,
  );

  return $payment_methods;
}

/**
 * Implements hook_cron
 */
function flg_payment_cron() {
  try {
    $orders = commerce_order_load_multiple(array(), array('status' => array('labuy', 'art_money', 'direct_deposit')), TRUE);

    foreach($orders as $order) {
      if(time() - $order->created >= 48 * 60 * 60) {
        $order_updated = commerce_order_status_update($order, 'payment_expire');
      }
    }

    watchdog('flg_payment', 'cron run success');
  } catch (\Throwable $th) {
    watchdog('flg_payment', 'cron run error !mess', array('!mess' => $th->getMessage()));
  }
}
