<?php
/**
 * @file
 */

 /**
  * implements hook_init
  */
function flg_checkout_panes_init() {
}

/**
 * implements hook_form_alter
 */
function flg_checkout_panes_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'commerce_checkout_form_account':
      $form['account_form']['select']['register']['continue']['#submit'][] = 'flg_checkout_panes_account_form_submit';
      break;
    
    default:
      # code...
      break;
  }
}

/**
 * account form submit form callback
 */
function flg_checkout_panes_account_form_submit($form, &$form_state) {
  global $user;
  $user = user_save(
    (object) array(
      'name' => $form_state['values']['account_form']['select']['register']['username'],
      'pass' => user_password(),
      'mail' => $form_state['values']['account_form']['select']['register']['mail'],
      'init' => $form_state['values']['account_form']['select']['register']['init'],
      'field_first_name' => $form_state['values']['account_form']['select']['register']['init'],
      'status' => 1,
      'roles' => array(6 => true)
    )
  );

  _user_mail_notify('register_no_approval_required', $user);
  drupal_set_message(t('Registration successful. You are now logged in.'));

  user_login_finalize();
  // drupal_session_regenerate();
}
